apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: luizalabs-api
  name: luizalabs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: luizalabs-api
  template:
    metadata:
      labels:
        io.kompose.service: luizalabs-api
    spec:
      containers:
      - image: ensleyribeiro/luizalabs-api:0.0.2-SNAPSHOT
        imagePullPolicy: ""
        name: luizalabs-api
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
