apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: postgres-server
  name: postgres-server
spec:
  type: LoadBalancer
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: postgres-server