language: java
sudo: required
dist: trusty
jdk: 
  - oraclejdk8
services:
  - docker
env:
  global:
    - PROJECT_VERSION=0.0.4
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - CLOUDSDK_PYTHON=python2.7
before_install:
  - openssl aes-256-cbc -K $encrypted_7370d2466cda_key -iv $encrypted_7370d2466cda_iv -in luizalabs-server-rest-d419598266fa.json.enc -out luizalabs-server-rest-d419598266fa.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file luizalabs-server-rest-d419598266fa.json
  - gcloud config set project luizalabs-server-rest
  - gcloud config set compute/zone southamerica-east1-a
  - gcloud container clusters get-credentials luizalabs
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cd luizalabs-server-rest
  - chmod +x mvnw
script:
  - ./mvnw clean package

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
