version: '3'
services:
  luizalabs-api:
    image: ensleyribeiro/luizalabs-api:0.0.3-RELEASE
    #build: .
    restart: always
    depends_on:
      - postgres-server
    ports:
      - "3000:3000"
  postgres-server:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: "luizalabs"
    ports:
    - "5432:5432"